export function getMainTs(): string {
  const backtick = '`';
  const dollar = '$';
  return [
    '// ThatOpen App — Default Template',
    '//',
    '// This is a minimal app that runs inside the That Open Platform.',
    '// It renders into the #that-open-app element in index.html.',
    '//',
    '// Platform context (window.__THATOPEN_CONTEXT__):',
    '//   appId       — this app\'s unique identifier',
    '//   projectId   — the project this app belongs to',
    '//   accessToken — Auth0 JWT for API calls',
    '//   apiUrl      — base URL for the That Open API',
    '//',
    '// To add BIM capabilities (3D viewer, model loading), install:',
    '//   npm install @thatopen/components @thatopen/ui three thatopen-services',
    '// Then see the "bim" template for the full pattern.',
    '',
    'import { EngineServicesClient } from "thatopen-services";',
    'import type { ProjectData } from "thatopen-services";',
    '',
    'interface ThatOpenContext {',
    '  appId: string;',
    '  projectId: string;',
    '  accessToken: string;',
    '  apiUrl: string;',
    '}',
    '',
    'declare global {',
    '  interface Window {',
    '    __THATOPEN_CONTEXT__?: ThatOpenContext;',
    '  }',
    '}',
    '',
    'const ctx = window.__THATOPEN_CONTEXT__ || {} as ThatOpenContext;',
    '',
    'async function main() {',
    '  const app = document.getElementById(\'that-open-app\')!;',
    '',
    '  // ─── Engine Services Client ───────────────────────────────────',
    '  const client = new EngineServicesClient(ctx.accessToken, ctx.apiUrl, { useBearer: true });',
    '',
    '  // ─── Project Data ───────────────────────────────────────────────',
    '  // Fetches project data (users, roles, files, folders) in one call.',
    '  let projectData: ProjectData | null = null;',
    '  if (ctx.projectId) {',
    '    try {',
    '      projectData = await client.getProjectData(ctx.projectId);',
    '    } catch (err) {',
    '      console.warn("Could not fetch project data:", err);',
    '    }',
    '  }',
    '',
    '  const projectTitle = projectData?.project.title || \'N/A\';',
    '  const userName = projectData?.currentUser?.user.fullName || \'N/A\';',
    '  const membersCount = projectData?.users.length ?? 0;',
    '  const filesCount = projectData?.files.length ?? 0;',
    '',
    '  // Render the app. Replace this with your own UI.',
    '  app.innerHTML = ' + backtick,
    '    <div style="padding: 32px; font-family: system-ui, sans-serif; max-width: 600px; margin: 0 auto;">',
    '      <h1 style="color: #6528e0; margin-bottom: 16px;">My ThatOpen App</h1>',
    '      <p style="margin-bottom: 8px;"><strong>Project:</strong> ' + dollar + '{projectTitle}</p>',
    '      <p style="margin-bottom: 8px;"><strong>User:</strong> ' + dollar + '{userName}</p>',
    '      <p style="margin-bottom: 8px;"><strong>Members:</strong> ' + dollar + '{membersCount}</p>',
    '      <p style="margin-bottom: 8px;"><strong>Files:</strong> ' + dollar + '{filesCount}</p>',
    '      <p style="color: #888; margin-top: 24px;">Edit <code>src/main.ts</code> to start building your app.</p>',
    '    </div>',
    '  ' + backtick + ';',
    '}',
    '',
    'main().catch(console.error);',
    '',
  ].join('\n');
}
