export function getMainBim(): string {
  const backtick = '`';
  const dollar = '$';

  return [
    'import * as THREE from "three";',
    'import * as OBC from "@thatopen/components";',
    'import * as OBF from "@thatopen/components-front";',
    'import * as FRAGS from "@thatopen/fragments";',
    'import * as BUI from "@thatopen/ui";',
    'import * as CUI from "@thatopen/ui-obc";',
    'import { EngineServicesClient, AppManager, ViewportManager } from "thatopen-services";',
    '',
    'import type { ProjectContext } from "thatopen-services";',
    '',
    'interface ThatOpenContext {',
    '  appId: string;',
    '  projectId: string;',
    '  accessToken: string;',
    '  apiUrl: string;',
    '}',
    '',
    'declare global {',
    '  interface Window {',
    '    __THATOPEN_CONTEXT__?: ThatOpenContext;',
    '  }',
    '}',
    '',
    'const ctx = window.__THATOPEN_CONTEXT__ || {} as ThatOpenContext;',
    '',
    '// Wrap in async function since IIFE format does not support top-level await.',
    'async function main() {',
    '  // ─── Engine Services Client ───────────────────────────────────',
    '  // Uses the auth context passed by the platform to make API calls.',
    '  // useBearer: true sends the token as an Authorization header (for Auth0 JWT)',
    '  // instead of as a query parameter (for platform API tokens).',
    '  const client = new EngineServicesClient(ctx.accessToken, ctx.apiUrl, { useBearer: true });',
    '',
    '  // ─── Project Context ──────────────────────────────────────────',
    '  // Fetches project data (users, roles, files, folders) in one call.',
    '  // User data is stripped of sensitive fields server-side.',
    '  let projectContext: ProjectContext | null = null;',
    '  if (ctx.projectId) {',
    '    try {',
    '      projectContext = await client.getProjectContext(ctx.projectId);',
    '      console.log(' + backtick + 'Project: ' + dollar + '{projectContext.project.title}' + backtick + ');',
    '      console.log(' + backtick + 'Current user: ' + dollar + '{projectContext.currentUser?.user.fullName}' + backtick + ');',
    '      console.log(' + backtick + 'Members: ' + dollar + '{projectContext.users.length}, Files: ' + dollar + '{projectContext.files.length}' + backtick + ');',
    '    } catch (err) {',
    '      console.warn("Could not fetch project context:", err);',
    '    }',
    '  }',
    '',
    '  // ─── OBC Components ───────────────────────────────────────────',
    '  const components = new OBC.Components();',
    '',
    '  BUI.Manager.init();',
    '',
    '  // ─── Built-in Components ─────────────────────────────────────',
    '  // Register all libraries once — every initBuiltInComponent call',
    '  // will use them automatically (no need to pass globals each time).',
    '  client.setBuiltInGlobals({ OBC, OBF, BUI, CUI, THREE, FRAGS });',
    '',
    '  // Load AppManager (app shell) and ViewportManager (3D viewport',
    '  // factory) from the platform. These are fetched at runtime and',
    '  // registered with the OBC component system.',
    '  await client.initBuiltInComponent(AppManager, components);',
    '  await client.initBuiltInComponent(ViewportManager, components);',
    '',
    '  // ─── 3D Viewport ──────────────────────────────────────────────',
    '  // ViewportManager creates a fully configured viewport with its own',
    '  // world (scene, camera, renderer) and auto-initialises fragments.',
    '  const viewports = components.get(ViewportManager);',
    '  const { element: viewerElement, world } = await viewports.create();',
    '',
    '  components.init();',
    '',
    '  // ─── Load a Model ────────────────────────────────────────────',
    '  // FragmentsManager handles .frag files (compact BIM geometry format).',
    '  // You can also load from platform storage:',
    '  //   const response = await client.downloadFile(fileId);',
    '  //   const buffer = await response.arrayBuffer();',
    '  const fragments = components.get(OBC.FragmentsManager);',
    '  const modelPath = "https://thatopen.github.io/engine_components/resources/frags/school_arq.frag";',
    '  const file = await fetch(modelPath);',
    '  const buffer = await file.arrayBuffer();',
    '  await fragments.core.load(buffer, { modelId: "school_arq" });',
    '',
    '  await world.camera.controls.setLookAt(68, 23, -8.5, 21.5, -5.5, 23);',
    '  await fragments.core.update(true);',
    '',
    '  // ─── Info Panel ────────────────────────────────────────────────',
    '  // Fetch files to verify the token works',
    '  let fileNames: string[] = [];',
    '  try {',
    '    const files = await client.listFiles();',
    '    fileNames = files.map((f) => f.name);',
    '    console.log(' + backtick + 'Loaded ' + dollar + '{files.length} files from API' + backtick + ');',
    '  } catch (err) {',
    '    console.warn("Could not fetch files:", err);',
    '    fileNames = ["(Could not load files — check token permissions)"];',
    '  }',
    '',
    '  const fileList = fileNames',
    '    .map((name) => BUI.html' + backtick + '<bim-label>' + dollar + '{name}</bim-label>' + backtick + ');',
    '',
    '  const panel = () => {',
    '    return BUI.html' + backtick + '',
    '      <bim-panel label="App Info">',
    '        <bim-panel-section label="Context">',
    '          <bim-label>App ID: ' + dollar + '{ctx.appId}</bim-label>',
    '          <bim-label>Project ID: ' + dollar + '{ctx.projectId}</bim-label>',
    '          <bim-label>API URL: ' + dollar + '{ctx.apiUrl}</bim-label>',
    '        </bim-panel-section>',
    '        <bim-panel-section label="Files (' + dollar + '{fileNames.length})">',
    '          ' + dollar + '{fileList}',
    '        </bim-panel-section>',
    '      </bim-panel>',
    '    ' + backtick + ';',
    '  };',
    '',
    '  // ─── App Shell ─────────────────────────────────────────────────',
    '  // AppManager creates a CSS grid layout with named element slots.',
    '  // "elements" maps names to HTMLElements or BUI template functions.',
    '  // "layouts" defines grid arrangements using CSS grid-template shorthand:',
    '  //   "areas" rows / columns',
    '  // A sidebar for switching layouts appears automatically when there',
    '  // are multiple layouts. Add an "icon" (Iconify name) for each.',
    '  //',
    '  // Other built-in components you can add:',
    '  //   LoadModelButton, ViewerToolbar, ModelsPanel, ClassificationsList,',
    '  //   ClashesList, ClippingsList, LengthMeasuringsList, AreaMeasuringsList,',
    '  //   ColorsPalette, HighlightersList, QtoComparisonList, QueriesHierarchy,',
    '  //   CustomViewLegend, ScreenshotAnnotator',
    '  // Load them the same way: client.initBuiltInComponent(Component, components, globals)',
    '  const app = components.get(AppManager);',
    '',
    '  app.setup = {',
    '    elements: {',
    '      viewer: viewerElement,',
    '      panel,',
    '    },',
    '    layouts: {',
    '      Viewer: { template: ' + backtick + '"viewer" 1fr / 1fr' + backtick + ' },',
    '      Split: {',
    '        template: ' + backtick + '"panel viewer" 1fr / 20rem 1fr' + backtick + ',',
    '        icon: "solar:settings-bold",',
    '      },',
    '    },',
    '  };',
    '',
    '  app.init();',
    '}',
    '',
    'main().catch(console.error);',
    '',
  ].join('\n');
}
