export function getMainTs(): string {
  const backtick = '`';
  const dollar = '$';
  return [
    '// ThatOpen App — Default Template',
    '//',
    '// This is a minimal app that runs inside the That Open Platform.',
    '// It renders into the #that-open-app element in index.html.',
    '//',
    '// Platform context (window.__THATOPEN_CONTEXT__):',
    '//   appId       — this app\'s unique identifier',
    '//   projectId   — the project this app belongs to',
    '//   accessToken — Auth0 JWT for API calls',
    '//   apiUrl      — base URL for the That Open API',
    '//',
    '// To add BIM capabilities (3D viewer, model loading), install:',
    '//   npm install @thatopen/components @thatopen/ui three thatopen-services',
    '// Then see the "bim" template for the full pattern.',
    '',
    'interface ThatOpenContext {',
    '  appId: string;',
    '  projectId: string;',
    '  accessToken: string;',
    '  apiUrl: string;',
    '}',
    '',
    'declare global {',
    '  interface Window {',
    '    __THATOPEN_CONTEXT__?: ThatOpenContext;',
    '  }',
    '}',
    '',
    'const ctx = window.__THATOPEN_CONTEXT__ || {} as ThatOpenContext;',
    'const app = document.getElementById(\'that-open-app\')!;',
    '',
    '// Render the app. Replace this with your own UI.',
    'app.innerHTML = ' + backtick,
    '  <div style="padding: 32px; font-family: system-ui, sans-serif; max-width: 600px; margin: 0 auto;">',
    '    <h1 style="color: #6528e0; margin-bottom: 16px;">My ThatOpen App</h1>',
    '    <p style="margin-bottom: 8px;"><strong>App ID:</strong> ' + dollar + '{ctx.appId || \'N/A\'}</p>',
    '    <p style="margin-bottom: 8px;"><strong>Project ID:</strong> ' + dollar + '{ctx.projectId || \'N/A\'}</p>',
    '    <p style="margin-bottom: 8px;"><strong>API URL:</strong> ' + dollar + '{ctx.apiUrl || \'N/A\'}</p>',
    '    <p style="color: #888; margin-top: 24px;">Edit <code>src/main.ts</code> to start building your app.</p>',
    '  </div>',
    backtick + ';',
    '',
  ].join('\n');
}
