export function getMainBim(): string {
  const backtick = '`';

  return [
    'import * as THREE from "three";',
    'import * as OBC from "@thatopen/components";',
    'import * as BUI from "@thatopen/ui";',
    '',
    'interface ThatOpenContext {',
    '  appId: string;',
    '  projectId: string;',
    '  accessToken: string;',
    '  apiUrl: string;',
    '}',
    '',
    'declare global {',
    '  interface Window {',
    '    __THATOPEN_CONTEXT__?: ThatOpenContext;',
    '  }',
    '}',
    '',
    'const ctx = window.__THATOPEN_CONTEXT__ || {} as ThatOpenContext;',
    '',
    '// Wrap in async function since IIFE format does not support top-level await.',
    'async function main() {',
    '  const container = document.getElementById("that-open-app")!;',
    '',
    '  // Set up the 3D world',
    '  const components = new OBC.Components();',
    '  const worlds = components.get(OBC.Worlds);',
    '',
    '  const world = worlds.create<',
    '    OBC.SimpleScene,',
    '    OBC.SimpleCamera,',
    '    OBC.SimpleRenderer',
    '  >();',
    '',
    '  world.scene = new OBC.SimpleScene(components);',
    '  world.renderer = new OBC.SimpleRenderer(components, container);',
    '  world.camera = new OBC.SimpleCamera(components);',
    '',
    '  components.init();',
    '  world.scene.setup();',
    '  world.scene.three.background = null;',
    '',
    '  // Set up the fragment loader',
    '  const workerUrl = "https://thatopen.github.io/engine_fragment/resources/worker.mjs";',
    '  const fetchedWorker = await fetch(workerUrl);',
    '  const workerBlob = await fetchedWorker.blob();',
    '  const workerFile = new File([workerBlob], "worker.mjs", { type: "text/javascript" });',
    '  const fragments = components.get(OBC.FragmentsManager);',
    '  fragments.init(URL.createObjectURL(workerFile));',
    '',
    '  world.camera.controls.addEventListener("update", () => fragments.core.update());',
    '',
    '  fragments.list.onItemSet.add(({ value: model }) => {',
    '    model.useCamera(world.camera.three);',
    '    world.scene.three.add(model.object);',
    '    fragments.core.update(true);',
    '  });',
    '',
    '  // Load a sample model',
    '  const modelPath = "https://thatopen.github.io/engine_components/resources/frags/school_arq.frag";',
    '  const file = await fetch(modelPath);',
    '  const buffer = await file.arrayBuffer();',
    '  await fragments.core.load(buffer, { modelId: "school_arq" });',
    '',
    '  await world.camera.controls.setLookAt(68, 23, -8.5, 21.5, -5.5, 23);',
    '  await fragments.core.update(true);',
    '',
    '  console.log(' + backtick + 'App "${ctx.appId}" loaded in project "${ctx.projectId}"' + backtick + ');',
    '}',
    '',
    'main().catch(console.error);',
    '',
  ].join('\n');
}
