export function getMainBim(): string {
  const backtick = '`';
  const dollar = '$';

  return [
    'import * as THREE from "three";',
    'import * as OBC from "@thatopen/components";',
    'import * as BUI from "@thatopen/ui";',
    'import { EngineServicesClient } from "thatopen-services";',
    '',
    'interface ThatOpenContext {',
    '  appId: string;',
    '  projectId: string;',
    '  accessToken: string;',
    '  apiUrl: string;',
    '}',
    '',
    'declare global {',
    '  interface Window {',
    '    __THATOPEN_CONTEXT__?: ThatOpenContext;',
    '  }',
    '}',
    '',
    'const ctx = window.__THATOPEN_CONTEXT__ || {} as ThatOpenContext;',
    '',
    '// Wrap in async function since IIFE format does not support top-level await.',
    'async function main() {',
    '  const container = document.getElementById("that-open-app")!;',
    '',
    '  // ─── Engine Services Client ───────────────────────────────────',
    '  // Uses the auth context passed by the platform to make API calls.',
    '  // useBearer: true sends the token as an Authorization header (for Auth0 JWT)',
    '  // instead of as a query parameter (for platform API tokens).',
    '  const client = new EngineServicesClient(ctx.accessToken, ctx.apiUrl, { useBearer: true });',
    '',
    '  // Fetch files to verify the token works',
    '  let fileNames: string[] = [];',
    '  try {',
    '    const files = await client.listFiles();',
    '    fileNames = files.map((f) => f.name);',
    '    console.log(' + backtick + 'Loaded ' + dollar + '{files.length} files from API' + backtick + ');',
    '  } catch (err) {',
    '    console.warn("Could not fetch files:", err);',
    '    fileNames = ["(Could not load files — check token permissions)"];',
    '  }',
    '',
    '  // ─── 3D World Setup ──────────────────────────────────────────',
    '  const components = new OBC.Components();',
    '  const worlds = components.get(OBC.Worlds);',
    '',
    '  const world = worlds.create<',
    '    OBC.SimpleScene,',
    '    OBC.SimpleCamera,',
    '    OBC.SimpleRenderer',
    '  >();',
    '',
    '  world.scene = new OBC.SimpleScene(components);',
    '  world.renderer = new OBC.SimpleRenderer(components, container);',
    '  world.camera = new OBC.SimpleCamera(components);',
    '',
    '  components.init();',
    '  world.scene.setup();',
    '  world.scene.three.background = null;',
    '',
    '  // Set up the fragment loader',
    '  const workerUrl = "https://thatopen.github.io/engine_fragment/resources/worker.mjs";',
    '  const fetchedWorker = await fetch(workerUrl);',
    '  const workerBlob = await fetchedWorker.blob();',
    '  const workerFile = new File([workerBlob], "worker.mjs", { type: "text/javascript" });',
    '  const fragments = components.get(OBC.FragmentsManager);',
    '  fragments.init(URL.createObjectURL(workerFile));',
    '',
    '  world.camera.controls.addEventListener("update", () => fragments.core.update());',
    '',
    '  fragments.list.onItemSet.add(({ value: model }) => {',
    '    model.useCamera(world.camera.three);',
    '    world.scene.three.add(model.object);',
    '    fragments.core.update(true);',
    '  });',
    '',
    '  // Load a sample model',
    '  const modelPath = "https://thatopen.github.io/engine_components/resources/frags/school_arq.frag";',
    '  const file = await fetch(modelPath);',
    '  const buffer = await file.arrayBuffer();',
    '  await fragments.core.load(buffer, { modelId: "school_arq" });',
    '',
    '  await world.camera.controls.setLookAt(68, 23, -8.5, 21.5, -5.5, 23);',
    '  await fragments.core.update(true);',
    '',
    '  // ─── UI Panel ────────────────────────────────────────────────',
    '  BUI.Manager.init();',
    '',
    '  const fileList = fileNames',
    '    .map((name) => ' + backtick + '<bim-label>' + dollar + '{name}</bim-label>' + backtick + ')',
    '    .join("\\n");',
    '',
    '  const panel = BUI.Component.create<BUI.PanelSection>(() => {',
    '    return BUI.html' + backtick + '',
    '      <bim-panel label="App Info" class="options-menu">',
    '        <bim-panel-section label="Context">',
    '          <bim-label>App ID: ' + dollar + '{ctx.appId}</bim-label>',
    '          <bim-label>Project ID: ' + dollar + '{ctx.projectId}</bim-label>',
    '          <bim-label>API URL: ' + dollar + '{ctx.apiUrl}</bim-label>',
    '        </bim-panel-section>',
    '        <bim-panel-section label="Files (' + dollar + '{fileNames.length})">',
    '          ' + dollar + '{fileList}',
    '        </bim-panel-section>',
    '      </bim-panel>',
    '    ' + backtick + ';',
    '  });',
    '',
    '  document.body.append(panel);',
    '',
    '  const button = BUI.Component.create<BUI.PanelSection>(() => {',
    '    return BUI.html' + backtick + '<bim-button class="phone-menu-toggler" icon="solar:settings-bold"',
    '      @click="' + dollar + '{() => {',
    '        panel.classList.toggle("options-menu-visible");',
    '      }}"></bim-button>' + backtick + ';',
    '  });',
    '',
    '  document.body.append(button);',
    '}',
    '',
    'main().catch(console.error);',
    '',
  ].join('\n');
}
