/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Built-in component types and runtime stubs.
 * Auto-generated by built-in-components/scripts/distribute.mjs
 */

import type * as OBC from '@thatopen/components';
import type * as BUI from '@thatopen/ui';
import type * as THREE from 'three';

/**
 * Configuration for an element slot in the app grid.
 * Can be a raw HTMLElement, a BUI stateless component, or a
 * BUI statefull component with initial state.
 */
type ElementDefinition = HTMLElement | (() => BUI.TemplateResult) | {
    template: (state: any, update: any) => BUI.TemplateResult;
    initialState: Record<string, any>;
};
/**
 * A named layout that maps element slots into a CSS grid template.
 * The `template` string uses CSS `grid-template-areas` syntax.
 * An optional `icon` can be shown in the sidebar button.
 */
interface LayoutDefinition {
    template: string;
    icon?: string;
}
/**
 * The setup configuration for the AppManager.
 * - `elements`: named UI slots that can be placed in layouts.
 * - `layouts`: named CSS grid templates that arrange the elements.
 */
interface AppManagerSetup {
    elements?: Record<string, ElementDefinition>;
    layouts: Record<string, LayoutDefinition>;
}
/**
 * Built-in component that structures a ThatOpen Platform application.
 *
 * AppManager creates the app shell: a content grid with named element
 * slots arranged by CSS grid layouts, and an optional sidebar that lets
 * the user switch between layouts.
 *
 * The sidebar is automatically shown when more than one layout is defined,
 * and hidden for single-layout apps.
 *
 * @example
 * ```ts
 * const app = components.get(AppManager);
 *
 * app.setup = {
 *   elements: {
 *     viewer: viewportElement,
 *     models: modelsPanel,
 *   },
 *   layouts: {
 *     Viewer: { template: `"viewer" 1fr / 1fr` },
 *     Split: { template: `"models viewer" 1fr / 15rem 1fr`, icon: "mdi:file-tree" },
 *   },
 * };
 *
 * app.init();
 * ```
 */
declare class _AppManager {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "2e32d873-02c9-421c-8743-d8a5ca6ad38a";
    enabled: boolean;
    readonly name = "AppManager";
    private _setup;
    private _grid;
    private _sidebarElement;
    private _container;
    /** Whether the app has been initialised via {@link init}. */
    private _initialized;
    constructor(components: any);
    /**
     * The setup configuration that defines elements and layouts.
     * Set this before calling {@link init}.
     */
    get setup(): AppManagerSetup | null;
    set setup(value: AppManagerSetup);
    /**
     * The underlying `<bim-grid>` element.
     * Available after {@link init} has been called.
     */
    get grid(): BUI.Grid | null;
    /**
     * The current active layout name, or `undefined` if not yet initialised.
     */
    get layout(): string | undefined;
    set layout(name: string);
    /**
     * Initialise the app and mount it into the DOM.
     *
     * @param container - The element to mount into. Defaults to `document.body`.
     */
    init(container?: HTMLElement): void;
    /**
     * Creates the sidebar element with layout-switching buttons.
     */
    private _createSidebar;
    /**
     * Highlights the active layout button in the sidebar.
     */
    private _updateSidebarActive;
    /**
     * Injects the component's CSS into the document head.
     */
    private _injectStyles;
}

/**
 * Built-in component that structures a ThatOpen Platform application.
 *
 * AppManager creates the app shell: a content grid with named element
 * slots arranged by CSS grid layouts, and an optional sidebar that lets
 * the user switch between layouts.
 *
 * The sidebar is automatically shown when more than one layout is defined,
 * and hidden for single-layout apps.
 *
 * @example
 * ```ts
 * const app = components.get(AppManager);
 *
 * app.setup = {
 *   elements: {
 *     viewer: viewportElement,
 *     models: modelsPanel,
 *   },
 *   layouts: {
 *     Viewer: { template: `"viewer" 1fr / 1fr` },
 *     Split: { template: `"models viewer" 1fr / 15rem 1fr`, icon: "mdi:file-tree" },
 *   },
 * };
 *
 * app.init();
 * ```
 */
export type AppManager = InstanceType<typeof _AppManager>;
/**
 * Built-in component that structures a ThatOpen Platform application.
 *
 * AppManager creates the app shell: a content grid with named element
 * slots arranged by CSS grid layouts, and an optional sidebar that lets
 * the user switch between layouts.
 *
 * The sidebar is automatically shown when more than one layout is defined,
 * and hidden for single-layout apps.
 *
 * @example
 * ```ts
 * const app = components.get(AppManager);
 *
 * app.setup = {
 *   elements: {
 *     viewer: viewportElement,
 *     models: modelsPanel,
 *   },
 *   layouts: {
 *     Viewer: { template: `"viewer" 1fr / 1fr` },
 *     Split: { template: `"models viewer" 1fr / 15rem 1fr`, icon: "mdi:file-tree" },
 *   },
 * };
 *
 * app.init();
 * ```
 */
export const AppManager = { uuid: '2e32d873-02c9-421c-8743-d8a5ca6ad38a' } as typeof _AppManager & { uuid: '2e32d873-02c9-421c-8743-d8a5ca6ad38a' };

/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
declare class _HelloWorld {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "2c4ae432-fc24-43e9-9783-0c960c674e96";
    enabled: boolean;
    readonly name = "HelloWorld";
    constructor(components: any);
    /**
     * Returns a greeting message and logs it to the console.
     * @param who - The name to greet. Defaults to `"World"`.
     */
    greet(who?: string): string;
}
/**
 * PlatformComponents.import() expects a `main` variable in scope with
 * a `componentDefinition` property pointing to the OBC.Component class.
 * The IIFE build (name: 'main') assigns this to `var main = ...`.
 */

/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export type HelloWorld = InstanceType<typeof _HelloWorld>;
/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export const HelloWorld = { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' } as typeof _HelloWorld & { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' };

/**
 * The result of creating a viewport instance via {@link ViewportManager.create}.
 */
interface ViewportInstance {
    /** The `<bim-viewport>` HTML element to mount in a layout slot. */
    element: BUI.Viewport;
    /** The Three.js world bound to this viewport. */
    world: OBC.SimpleWorld<OBC.SimpleScene, OBC.OrthoPerspectiveCamera, OBC.SimpleRenderer>;
}
/**
 * Optional configuration when creating a viewport instance.
 */
interface ViewportConfig {
    /** Background color for the scene. Set to `null` for transparent. Defaults to `null`. */
    backgroundColor?: THREE.ColorRepresentation | null;
    /** Grid color. Defaults to `"lightgray"`. */
    gridColor?: THREE.ColorRepresentation;
}
/**
 * Built-in component that creates 3D viewports with a pre-configured
 * world (scene, camera, renderer) and fragments manager.
 *
 * ViewportManager is a factory: each call to {@link create} returns a
 * new independent viewport with its own world. The component tracks all
 * created instances and cleans them up on {@link dispose}.
 *
 * @example
 * ```ts
 * const viewports = components.get(ViewportManager);
 * const { element, world } = await viewports.create();
 *
 * // Use `element` as a slot in AppManager
 * app.setup = {
 *   elements: { viewer: element },
 *   layouts: { Main: { template: `"viewer" 1fr / 1fr` } },
 * };
 * ```
 */
declare class _ViewportManager {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "def81d43-6b44-4f4a-9c08-7649486112a4";
    enabled: boolean;
    readonly name = "ViewportManager";
    private _instances;
    private _fragmentsInitialized;
    constructor(components: any);
    /**
     * Creates a new viewport instance with its own world, scene, camera,
     * and renderer. Fragments manager is initialised automatically on
     * the first call.
     *
     * @param config - Optional visual configuration for the viewport.
     * @returns A {@link ViewportInstance} containing the DOM element and world.
     */
    create(config?: ViewportConfig): Promise<ViewportInstance>;
    /**
     * Disposes all created viewport instances and their worlds.
     */
    dispose(): void;
    /**
     * Initialises the fragments manager if not yet done, and wires up
     * model loading for the given world.
     */
    private _initFragments;
}

/**
 * Built-in component that creates 3D viewports with a pre-configured
 * world (scene, camera, renderer) and fragments manager.
 *
 * ViewportManager is a factory: each call to {@link create} returns a
 * new independent viewport with its own world. The component tracks all
 * created instances and cleans them up on {@link dispose}.
 *
 * @example
 * ```ts
 * const viewports = components.get(ViewportManager);
 * const { element, world } = await viewports.create();
 *
 * // Use `element` as a slot in AppManager
 * app.setup = {
 *   elements: { viewer: element },
 *   layouts: { Main: { template: `"viewer" 1fr / 1fr` } },
 * };
 * ```
 */
export type ViewportManager = InstanceType<typeof _ViewportManager>;
/**
 * Built-in component that creates 3D viewports with a pre-configured
 * world (scene, camera, renderer) and fragments manager.
 *
 * ViewportManager is a factory: each call to {@link create} returns a
 * new independent viewport with its own world. The component tracks all
 * created instances and cleans them up on {@link dispose}.
 *
 * @example
 * ```ts
 * const viewports = components.get(ViewportManager);
 * const { element, world } = await viewports.create();
 *
 * // Use `element` as a slot in AppManager
 * app.setup = {
 *   elements: { viewer: element },
 *   layouts: { Main: { template: `"viewer" 1fr / 1fr` } },
 * };
 * ```
 */
export const ViewportManager = { uuid: 'def81d43-6b44-4f4a-9c08-7649486112a4' } as typeof _ViewportManager & { uuid: 'def81d43-6b44-4f4a-9c08-7649486112a4' };
