/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Built-in component types and runtime stubs.
 * Auto-generated by built-in-components/scripts/distribute.mjs
 */

import type * as OBC from '@thatopen/components';
import type * as BUI from '@thatopen/ui';
import type * as THREE from 'three';

/**
 * Configuration for an element slot in the app grid.
 * Can be a raw HTMLElement, a BUI stateless component, or a
 * BUI statefull component with initial state.
 */
type ElementDefinition = HTMLElement | (() => BUI.TemplateResult) | {
    template: (state: any, update: any) => BUI.TemplateResult;
    initialState: Record<string, any>;
};
/**
 * A named layout that maps element slots into a CSS grid template.
 * The `template` string uses CSS `grid-template-areas` syntax.
 * An optional `icon` can be shown in the sidebar button.
 */
interface LayoutDefinition {
    template: string;
    icon?: string;
}
/**
 * The setup configuration for the AppManager.
 * - `elements`: named UI slots that can be placed in layouts.
 * - `layouts`: named CSS grid templates that arrange the elements.
 */
interface AppManagerSetup {
    elements?: Record<string, ElementDefinition>;
    layouts: Record<string, LayoutDefinition>;
    showSidebar?: boolean;
}
/**
 * Built-in component that structures a ThatOpen Platform application.
 *
 * AppManager creates the app shell: a content grid with named element
 * slots arranged by CSS grid layouts, and an optional sidebar that lets
 * the user switch between layouts.
 *
 * The sidebar is automatically shown when more than one layout is defined,
 * and hidden for single-layout apps.
 *
 * @example
 * ```ts
 * const app = components.get(AppManager);
 *
 * app.setup = {
 *   elements: {
 *     viewer: viewportElement,
 *     models: modelsPanel,
 *   },
 *   layouts: {
 *     Viewer: { template: `"viewer" 1fr / 1fr` },
 *     Split: { template: `"models viewer" 1fr / 15rem 1fr`, icon: "mdi:file-tree" },
 *   },
 * };
 *
 * app.init();
 * ```
 */
declare class _AppManager {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "2e32d873-02c9-421c-8743-d8a5ca6ad38a";
    enabled: boolean;
    readonly name = "AppManager";
    private _setup;
    private _grid;
    private _sidebarElement;
    private _container;
    /** Whether the app has been initialised via {@link init}. */
    private _initialized;
    constructor(components: any);
    /**
     * The setup configuration that defines elements and layouts.
     * Set this before calling {@link init}.
     */
    get setup(): AppManagerSetup | null;
    set setup(value: AppManagerSetup);
    /**
     * The underlying `<bim-grid>` element.
     * Available after {@link init} has been called.
     */
    get grid(): BUI.Grid | null;
    /**
     * The current active layout name, or `undefined` if not yet initialised.
     */
    get layout(): string | undefined;
    set layout(name: string);
    /**
     * Initialise the app and mount it into the DOM.
     *
     * @param container - The element to mount into. Defaults to `document.body`.
     */
    init(container?: HTMLElement): void;
    /**
     * Creates the sidebar element with layout-switching buttons.
     */
    private _createSidebar;
    /**
     * Highlights the active layout button in the sidebar.
     */
    private _updateSidebarActive;
    /**
     * Injects the component's CSS into the document head.
     */
    private _injectStyles;
}

/**
 * Built-in component that structures a ThatOpen Platform application.
 *
 * AppManager creates the app shell: a content grid with named element
 * slots arranged by CSS grid layouts, and an optional sidebar that lets
 * the user switch between layouts.
 *
 * The sidebar is automatically shown when more than one layout is defined,
 * and hidden for single-layout apps.
 *
 * @example
 * ```ts
 * const app = components.get(AppManager);
 *
 * app.setup = {
 *   elements: {
 *     viewer: viewportElement,
 *     models: modelsPanel,
 *   },
 *   layouts: {
 *     Viewer: { template: `"viewer" 1fr / 1fr` },
 *     Split: { template: `"models viewer" 1fr / 15rem 1fr`, icon: "mdi:file-tree" },
 *   },
 * };
 *
 * app.init();
 * ```
 */
export type AppManager = InstanceType<typeof _AppManager>;
/**
 * Built-in component that structures a ThatOpen Platform application.
 *
 * AppManager creates the app shell: a content grid with named element
 * slots arranged by CSS grid layouts, and an optional sidebar that lets
 * the user switch between layouts.
 *
 * The sidebar is automatically shown when more than one layout is defined,
 * and hidden for single-layout apps.
 *
 * @example
 * ```ts
 * const app = components.get(AppManager);
 *
 * app.setup = {
 *   elements: {
 *     viewer: viewportElement,
 *     models: modelsPanel,
 *   },
 *   layouts: {
 *     Viewer: { template: `"viewer" 1fr / 1fr` },
 *     Split: { template: `"models viewer" 1fr / 15rem 1fr`, icon: "mdi:file-tree" },
 *   },
 * };
 *
 * app.init();
 * ```
 */
export const AppManager = { uuid: '2e32d873-02c9-421c-8743-d8a5ca6ad38a' } as typeof _AppManager & { uuid: '2e32d873-02c9-421c-8743-d8a5ca6ad38a' };

/**
 * Configuration for creating an area measurings list.
 */
interface AreaMeasuringsConfig {
    /** Whether to auto-update when measurements change. Defaults to `true`. */
    autoUpdate?: boolean;
    /** Message shown when no measurements exist. */
    missingDataMessage?: string;
}
/**
 * Built-in component that creates a panel listing all area measurements
 * with individual area/perimeter values, cumulative totals, and action buttons.
 *
 * Each measurement row shows the measured area and provides controls
 * to toggle visibility, fly the camera to it, and delete.
 * Auto-updates as measurements are added or removed.
 *
 * @example
 * ```ts
 * const list = components.get(AreaMeasuringsList);
 * const element = list.create(world);
 * panel.appendChild(element);
 * ```
 */
declare class _AreaMeasuringsList {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "42142fd6-c5e8-4736-9f77-0cd428454732";
    enabled: boolean;
    readonly name = "AreaMeasuringsList";
    constructor(components: any);
    /**
     * Creates an area measurings list element.
     *
     * @param world - The world containing the measurements.
     * @param config - Optional configuration.
     * @returns An HTMLElement containing the measurements table.
     */
    create(world: OBC.World, config?: AreaMeasuringsConfig): HTMLElement;
}

/**
 * Built-in component that creates a panel listing all area measurements
 * with individual area/perimeter values, cumulative totals, and action buttons.
 *
 * Each measurement row shows the measured area and provides controls
 * to toggle visibility, fly the camera to it, and delete.
 * Auto-updates as measurements are added or removed.
 *
 * @example
 * ```ts
 * const list = components.get(AreaMeasuringsList);
 * const element = list.create(world);
 * panel.appendChild(element);
 * ```
 */
export type AreaMeasuringsList = InstanceType<typeof _AreaMeasuringsList>;
/**
 * Built-in component that creates a panel listing all area measurements
 * with individual area/perimeter values, cumulative totals, and action buttons.
 *
 * Each measurement row shows the measured area and provides controls
 * to toggle visibility, fly the camera to it, and delete.
 * Auto-updates as measurements are added or removed.
 *
 * @example
 * ```ts
 * const list = components.get(AreaMeasuringsList);
 * const element = list.create(world);
 * panel.appendChild(element);
 * ```
 */
export const AreaMeasuringsList = { uuid: '42142fd6-c5e8-4736-9f77-0cd428454732' } as typeof _AreaMeasuringsList & { uuid: '42142fd6-c5e8-4736-9f77-0cd428454732' };

/**
 * Data for a single clash between two elements.
 */
interface ClashData {
    /** Display name for the clash (e.g., "Clash #1"). */
    name: string;
    /** Model-to-localIds map for the first clashing element. */
    elementA: OBC.ModelIdMap;
    /** Model-to-localIds map for the second clashing element. */
    elementB: OBC.ModelIdMap;
    /** Distance between the two elements. */
    distance: number;
}
/**
 * Configuration for creating a clashes list.
 */
interface ClashesListConfig {
    /** Static array of clashes to display. */
    clashes?: ClashData[];
    /** Async function to load clashes dynamically. */
    loadFunction?: () => Promise<ClashData[]>;
    /** Pair of hex colors for highlighting element A and B. Defaults to `['#ef9a9a', '#90caf9']`. */
    highlightColors?: [string, string];
    /** Message shown when no clashes exist. */
    missingDataMessage?: string;
}
/**
 * Built-in component that creates an interactive clash detection results
 * table with click-to-highlight functionality.
 *
 * Each row shows the clash name, element names, and distance. Clicking
 * a row highlights both clashing elements in different colors and fits
 * the camera to them.
 *
 * @example
 * ```ts
 * const list = components.get(ClashesList);
 * const element = list.create(world, {
 *   clashes: [
 *     {
 *       name: 'Clash #1',
 *       elementA: { modelId: new Set([100]) },
 *       elementB: { modelId: new Set([200]) },
 *       distance: 4.2,
 *     },
 *   ],
 * });
 * panel.appendChild(element);
 * ```
 */
declare class _ClashesList {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "79cfa8ce-c579-45e2-b737-7023ca6d9a62";
    enabled: boolean;
    readonly name = "ClashesList";
    constructor(components: any);
    /**
     * Creates a clashes list element.
     *
     * @param world - The world for camera and highlighting.
     * @param config - Configuration with clash data and options.
     * @returns An HTMLElement containing the clashes table.
     */
    create(world: OBC.World, config: ClashesListConfig): HTMLElement;
}

/**
 * Built-in component that creates an interactive clash detection results
 * table with click-to-highlight functionality.
 *
 * Each row shows the clash name, element names, and distance. Clicking
 * a row highlights both clashing elements in different colors and fits
 * the camera to them.
 *
 * @example
 * ```ts
 * const list = components.get(ClashesList);
 * const element = list.create(world, {
 *   clashes: [
 *     {
 *       name: 'Clash #1',
 *       elementA: { modelId: new Set([100]) },
 *       elementB: { modelId: new Set([200]) },
 *       distance: 4.2,
 *     },
 *   ],
 * });
 * panel.appendChild(element);
 * ```
 */
export type ClashesList = InstanceType<typeof _ClashesList>;
/**
 * Built-in component that creates an interactive clash detection results
 * table with click-to-highlight functionality.
 *
 * Each row shows the clash name, element names, and distance. Clicking
 * a row highlights both clashing elements in different colors and fits
 * the camera to them.
 *
 * @example
 * ```ts
 * const list = components.get(ClashesList);
 * const element = list.create(world, {
 *   clashes: [
 *     {
 *       name: 'Clash #1',
 *       elementA: { modelId: new Set([100]) },
 *       elementB: { modelId: new Set([200]) },
 *       distance: 4.2,
 *     },
 *   ],
 * });
 * panel.appendChild(element);
 * ```
 */
export const ClashesList = { uuid: '79cfa8ce-c579-45e2-b737-7023ca6d9a62' } as typeof _ClashesList & { uuid: '79cfa8ce-c579-45e2-b737-7023ca6d9a62' };

/**
 * Configuration for creating a classifications list.
 */
interface ClassificationsListConfig {
    /** Message shown when no classifications exist. */
    missingDataMessage?: string;
}
/**
 * Built-in component that creates a hierarchical table browsing IFC
 * classification data (ClassificationReference items).
 *
 * Groups classifications by system name, then by code. Each code row
 * has an action button to highlight the classified elements in the 3D view.
 *
 * @example
 * ```ts
 * const list = components.get(ClassificationsList);
 * const element = list.create();
 * panel.appendChild(element);
 * ```
 */
declare class _ClassificationsList {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "7358c9f0-7478-4a89-80fb-637d2e4fab97";
    enabled: boolean;
    readonly name = "ClassificationsList";
    constructor(components: any);
    /**
     * Creates a classifications list element.
     *
     * @param config - Optional configuration.
     * @returns An HTMLElement containing the classifications table.
     */
    create(config?: ClassificationsListConfig): HTMLElement;
}

/**
 * Built-in component that creates a hierarchical table browsing IFC
 * classification data (ClassificationReference items).
 *
 * Groups classifications by system name, then by code. Each code row
 * has an action button to highlight the classified elements in the 3D view.
 *
 * @example
 * ```ts
 * const list = components.get(ClassificationsList);
 * const element = list.create();
 * panel.appendChild(element);
 * ```
 */
export type ClassificationsList = InstanceType<typeof _ClassificationsList>;
/**
 * Built-in component that creates a hierarchical table browsing IFC
 * classification data (ClassificationReference items).
 *
 * Groups classifications by system name, then by code. Each code row
 * has an action button to highlight the classified elements in the 3D view.
 *
 * @example
 * ```ts
 * const list = components.get(ClassificationsList);
 * const element = list.create();
 * panel.appendChild(element);
 * ```
 */
export const ClassificationsList = { uuid: '7358c9f0-7478-4a89-80fb-637d2e4fab97' } as typeof _ClassificationsList & { uuid: '7358c9f0-7478-4a89-80fb-637d2e4fab97' };

/**
 * Configuration for creating a clippings list.
 */
interface ClippingsListConfig {
    /** Whether to auto-update when clipping planes change. Defaults to `true`. */
    autoUpdate?: boolean;
    /** Message shown when no clipping planes exist. */
    missingDataMessage?: string;
}
/**
 * Built-in component that creates a panel listing all active clipping planes
 * with controls to enable/disable, navigate to, and delete each plane.
 *
 * Auto-updates as clipping planes are added or removed via {@link OBC.Clipper}.
 *
 * @example
 * ```ts
 * const list = components.get(ClippingsList);
 * const element = list.create();
 * panel.appendChild(element);
 * ```
 */
declare class _ClippingsList {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "dbfe46a4-c8f2-4e0b-a9f0-8e65f52815f8";
    enabled: boolean;
    readonly name = "ClippingsList";
    constructor(components: any);
    /**
     * Creates a clippings list element.
     *
     * @param config - Optional configuration.
     * @returns An HTMLElement containing the clippings table.
     */
    create(config?: ClippingsListConfig): HTMLElement;
}

/**
 * Built-in component that creates a panel listing all active clipping planes
 * with controls to enable/disable, navigate to, and delete each plane.
 *
 * Auto-updates as clipping planes are added or removed via {@link OBC.Clipper}.
 *
 * @example
 * ```ts
 * const list = components.get(ClippingsList);
 * const element = list.create();
 * panel.appendChild(element);
 * ```
 */
export type ClippingsList = InstanceType<typeof _ClippingsList>;
/**
 * Built-in component that creates a panel listing all active clipping planes
 * with controls to enable/disable, navigate to, and delete each plane.
 *
 * Auto-updates as clipping planes are added or removed via {@link OBC.Clipper}.
 *
 * @example
 * ```ts
 * const list = components.get(ClippingsList);
 * const element = list.create();
 * panel.appendChild(element);
 * ```
 */
export const ClippingsList = { uuid: 'dbfe46a4-c8f2-4e0b-a9f0-8e65f52815f8' } as typeof _ClippingsList & { uuid: 'dbfe46a4-c8f2-4e0b-a9f0-8e65f52815f8' };

/**
 * Configuration for creating a colors palette instance.
 */
interface ColorsPaletteConfig {
    /** Callback invoked when the user applies a color. */
    onApply: (color: string, name?: string) => void | Promise<void>;
    /** Override the default pastel color set. */
    defaultColors?: string[];
    /** Whether to include existing Highlighter styles as named swatches. Defaults to `true`. */
    addHighlighterColors?: boolean;
}
/**
 * Built-in component that creates color picker palettes for BIM highlighting.
 *
 * Each call to {@link create} returns a self-contained DOM element with a
 * grid of color swatches, a custom-color input, and an Apply button.
 * When Highlighter styles exist, they appear as named swatches so users
 * can quickly reapply known highlight colors.
 *
 * @example
 * ```ts
 * const palette = components.get(ColorsPalette);
 * const element = palette.create({
 *   onApply: (color, name) => console.log('Selected:', color, name),
 * });
 * document.body.appendChild(element);
 * ```
 */
declare class _ColorsPalette {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "fc80758c-d543-4316-ba86-56164634d25a";
    enabled: boolean;
    readonly name = "ColorsPalette";
    constructor(components: any);
    /**
     * Creates a color palette element.
     *
     * @param config - Configuration with the apply callback and optional color overrides.
     * @returns An HTMLElement containing the palette UI.
     */
    create(config: ColorsPaletteConfig): HTMLElement;
}

/**
 * Built-in component that creates color picker palettes for BIM highlighting.
 *
 * Each call to {@link create} returns a self-contained DOM element with a
 * grid of color swatches, a custom-color input, and an Apply button.
 * When Highlighter styles exist, they appear as named swatches so users
 * can quickly reapply known highlight colors.
 *
 * @example
 * ```ts
 * const palette = components.get(ColorsPalette);
 * const element = palette.create({
 *   onApply: (color, name) => console.log('Selected:', color, name),
 * });
 * document.body.appendChild(element);
 * ```
 */
export type ColorsPalette = InstanceType<typeof _ColorsPalette>;
/**
 * Built-in component that creates color picker palettes for BIM highlighting.
 *
 * Each call to {@link create} returns a self-contained DOM element with a
 * grid of color swatches, a custom-color input, and an Apply button.
 * When Highlighter styles exist, they appear as named swatches so users
 * can quickly reapply known highlight colors.
 *
 * @example
 * ```ts
 * const palette = components.get(ColorsPalette);
 * const element = palette.create({
 *   onApply: (color, name) => console.log('Selected:', color, name),
 * });
 * document.body.appendChild(element);
 * ```
 */
export const ColorsPalette = { uuid: 'fc80758c-d543-4316-ba86-56164634d25a' } as typeof _ColorsPalette & { uuid: 'fc80758c-d543-4316-ba86-56164634d25a' };

/**
 * Configuration for creating a view legend overlay.
 */
interface ViewLegendConfig {
    /** Map of hex color strings to sets of label names. */
    colors: Record<string, Set<string>>;
}
/**
 * Built-in component that creates a simple color legend overlay.
 *
 * Renders a list of colored circles with associated label text,
 * positioned as an absolute overlay on the left side of its container.
 *
 * @example
 * ```ts
 * const legend = components.get(CustomViewLegend);
 * const element = legend.create({
 *   colors: {
 *     '#ef9a9a': new Set(['Walls', 'Slabs']),
 *     '#a5d6a7': new Set(['Columns']),
 *   },
 * });
 * container.appendChild(element);
 * ```
 */
declare class _CustomViewLegend {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "0e009adb-30aa-4842-a5f5-b8909c82c3e7";
    enabled: boolean;
    readonly name = "CustomViewLegend";
    constructor(components: any);
    /**
     * Creates a color legend overlay element.
     *
     * @param config - Configuration with color-to-labels mapping.
     * @returns An HTMLElement containing the legend UI.
     */
    create(config: ViewLegendConfig): HTMLElement;
}

/**
 * Built-in component that creates a simple color legend overlay.
 *
 * Renders a list of colored circles with associated label text,
 * positioned as an absolute overlay on the left side of its container.
 *
 * @example
 * ```ts
 * const legend = components.get(CustomViewLegend);
 * const element = legend.create({
 *   colors: {
 *     '#ef9a9a': new Set(['Walls', 'Slabs']),
 *     '#a5d6a7': new Set(['Columns']),
 *   },
 * });
 * container.appendChild(element);
 * ```
 */
export type CustomViewLegend = InstanceType<typeof _CustomViewLegend>;
/**
 * Built-in component that creates a simple color legend overlay.
 *
 * Renders a list of colored circles with associated label text,
 * positioned as an absolute overlay on the left side of its container.
 *
 * @example
 * ```ts
 * const legend = components.get(CustomViewLegend);
 * const element = legend.create({
 *   colors: {
 *     '#ef9a9a': new Set(['Walls', 'Slabs']),
 *     '#a5d6a7': new Set(['Columns']),
 *   },
 * });
 * container.appendChild(element);
 * ```
 */
export const CustomViewLegend = { uuid: '0e009adb-30aa-4842-a5f5-b8909c82c3e7' } as typeof _CustomViewLegend & { uuid: '0e009adb-30aa-4842-a5f5-b8909c82c3e7' };

/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
declare class _HelloWorld {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "2c4ae432-fc24-43e9-9783-0c960c674e96";
    enabled: boolean;
    readonly name = "HelloWorld";
    constructor(components: any);
    /**
     * Returns a greeting message and logs it to the console.
     * @param who - The name to greet. Defaults to `"World"`.
     */
    greet(who?: string): string;
}
/**
 * PlatformComponents.import() expects a `main` variable in scope with
 * a `componentDefinition` property pointing to the OBC.Component class.
 * The IIFE build (name: 'main') assigns this to `var main = ...`.
 */

/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export type HelloWorld = InstanceType<typeof _HelloWorld>;
/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export const HelloWorld = { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' } as typeof _HelloWorld & { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' };

/**
 * Configuration for creating a highlighters list.
 */
interface HighlightersListConfig {
    /** Whether to auto-update when highlight styles change. Defaults to `true`. */
    autoUpdate?: boolean;
    /** Message shown when no highlight styles exist. */
    missingDataMessage?: string;
}
/**
 * Built-in component that creates a panel listing all Highlighter styles
 * with color swatches and a context menu for managing each style.
 *
 * Filters out the built-in "select" style. Each style shows a colored
 * circle and its name. The context menu allows selecting, applying,
 * clearing, and deleting highlight styles.
 *
 * @example
 * ```ts
 * const list = components.get(HighlightersList);
 * const element = list.create();
 * panel.appendChild(element);
 * ```
 */
declare class _HighlightersList {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "01717a03-9dc8-4c79-afc1-c9cf1f7e23de";
    enabled: boolean;
    readonly name = "HighlightersList";
    constructor(components: any);
    /**
     * Creates a highlighters list element.
     *
     * @param config - Optional configuration.
     * @returns An HTMLElement containing the highlighters table.
     */
    create(config?: HighlightersListConfig): HTMLElement;
}

/**
 * Built-in component that creates a panel listing all Highlighter styles
 * with color swatches and a context menu for managing each style.
 *
 * Filters out the built-in "select" style. Each style shows a colored
 * circle and its name. The context menu allows selecting, applying,
 * clearing, and deleting highlight styles.
 *
 * @example
 * ```ts
 * const list = components.get(HighlightersList);
 * const element = list.create();
 * panel.appendChild(element);
 * ```
 */
export type HighlightersList = InstanceType<typeof _HighlightersList>;
/**
 * Built-in component that creates a panel listing all Highlighter styles
 * with color swatches and a context menu for managing each style.
 *
 * Filters out the built-in "select" style. Each style shows a colored
 * circle and its name. The context menu allows selecting, applying,
 * clearing, and deleting highlight styles.
 *
 * @example
 * ```ts
 * const list = components.get(HighlightersList);
 * const element = list.create();
 * panel.appendChild(element);
 * ```
 */
export const HighlightersList = { uuid: '01717a03-9dc8-4c79-afc1-c9cf1f7e23de' } as typeof _HighlightersList & { uuid: '01717a03-9dc8-4c79-afc1-c9cf1f7e23de' };

/**
 * Configuration for creating a length measurings list.
 */
interface MeasuringsConfig {
    /** Whether to auto-update when measurements change. Defaults to `true`. */
    autoUpdate?: boolean;
    /** Message shown when no measurements exist. */
    missingDataMessage?: string;
}
/**
 * Built-in component that creates a panel listing all length measurements
 * with individual values, a cumulative total, and action buttons.
 *
 * Each measurement row shows the measured length and provides controls
 * to fly the camera to the measurement, toggle display modes, and delete.
 * Auto-updates as measurements are added or removed.
 *
 * @example
 * ```ts
 * const list = components.get(LengthMeasuringsList);
 * const element = list.create(world);
 * panel.appendChild(element);
 * ```
 */
declare class _LengthMeasuringsList {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "7d8568f5-10bf-433d-a089-66e30e61d11c";
    enabled: boolean;
    readonly name = "LengthMeasuringsList";
    constructor(components: any);
    /**
     * Creates a length measurings list element.
     *
     * @param world - The world containing the measurements.
     * @param config - Optional configuration.
     * @returns An HTMLElement containing the measurements table.
     */
    create(world: OBC.World, config?: MeasuringsConfig): HTMLElement;
}

/**
 * Built-in component that creates a panel listing all length measurements
 * with individual values, a cumulative total, and action buttons.
 *
 * Each measurement row shows the measured length and provides controls
 * to fly the camera to the measurement, toggle display modes, and delete.
 * Auto-updates as measurements are added or removed.
 *
 * @example
 * ```ts
 * const list = components.get(LengthMeasuringsList);
 * const element = list.create(world);
 * panel.appendChild(element);
 * ```
 */
export type LengthMeasuringsList = InstanceType<typeof _LengthMeasuringsList>;
/**
 * Built-in component that creates a panel listing all length measurements
 * with individual values, a cumulative total, and action buttons.
 *
 * Each measurement row shows the measured length and provides controls
 * to fly the camera to the measurement, toggle display modes, and delete.
 * Auto-updates as measurements are added or removed.
 *
 * @example
 * ```ts
 * const list = components.get(LengthMeasuringsList);
 * const element = list.create(world);
 * panel.appendChild(element);
 * ```
 */
export const LengthMeasuringsList = { uuid: '7d8568f5-10bf-433d-a089-66e30e61d11c' } as typeof _LengthMeasuringsList & { uuid: '7d8568f5-10bf-433d-a089-66e30e61d11c' };

/**
 * Configuration for creating a load-model button.
 */
interface LoadModelButtonConfig {
    /** Which file types to offer. Defaults to both. */
    types?: {
        ifc?: boolean;
        fragments?: boolean;
    };
    /** Optional callback after an IFC model is processed. */
    onIfcProcessed?: (model: any) => void | Promise<void>;
}
/**
 * Built-in component that creates a button for loading BIM models.
 *
 * Supports loading IFC files (via {@link OBC.IfcLoader}) and
 * pre-processed Fragments files (via {@link OBC.FragmentsManager}).
 * The button shows a context menu dropdown with the available file types.
 *
 * @example
 * ```ts
 * const loader = components.get(LoadModelButton);
 * const btn = loader.create(world);
 * toolbar.appendChild(btn);
 * ```
 */
declare class _LoadModelButton {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "5707cb2d-718f-4d82-9944-cc7d9aa9b9a4";
    enabled: boolean;
    readonly name = "LoadModelButton";
    constructor(components: any);
    /**
     * Creates a load-model button element.
     *
     * @param world - The world to load models into.
     * @param config - Optional configuration for file types and callbacks.
     * @returns An HTMLElement containing the button with file-type dropdown.
     */
    create(world: OBC.World, config?: LoadModelButtonConfig): HTMLElement;
}

/**
 * Built-in component that creates a button for loading BIM models.
 *
 * Supports loading IFC files (via {@link OBC.IfcLoader}) and
 * pre-processed Fragments files (via {@link OBC.FragmentsManager}).
 * The button shows a context menu dropdown with the available file types.
 *
 * @example
 * ```ts
 * const loader = components.get(LoadModelButton);
 * const btn = loader.create(world);
 * toolbar.appendChild(btn);
 * ```
 */
export type LoadModelButton = InstanceType<typeof _LoadModelButton>;
/**
 * Built-in component that creates a button for loading BIM models.
 *
 * Supports loading IFC files (via {@link OBC.IfcLoader}) and
 * pre-processed Fragments files (via {@link OBC.FragmentsManager}).
 * The button shows a context menu dropdown with the available file types.
 *
 * @example
 * ```ts
 * const loader = components.get(LoadModelButton);
 * const btn = loader.create(world);
 * toolbar.appendChild(btn);
 * ```
 */
export const LoadModelButton = { uuid: '5707cb2d-718f-4d82-9944-cc7d9aa9b9a4' } as typeof _LoadModelButton & { uuid: '5707cb2d-718f-4d82-9944-cc7d9aa9b9a4' };

/**
 * Configuration for creating a models dropdown.
 */
interface ModelsDropdownConfig {
    /** Whether to auto-update when models are loaded/unloaded. Defaults to `true`. */
    autoUpdate?: boolean;
    /** Placeholder text. Defaults to `"Select models..."`. */
    placeholder?: string;
    /** Whether multiple models can be selected. Defaults to `true`. */
    multiple?: boolean;
}
/**
 * Built-in component that creates a dropdown listing all loaded BIM models.
 *
 * The dropdown auto-updates as models are loaded or unloaded via
 * {@link OBC.FragmentsManager}. Each option shows the model ID.
 *
 * @example
 * ```ts
 * const selector = components.get(ModelsDropdown);
 * const element = selector.create();
 * panel.appendChild(element);
 * ```
 */
declare class _ModelsDropdown {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "2496d0d7-ce8d-4683-92cb-615c524df0ca";
    enabled: boolean;
    readonly name = "ModelsDropdown";
    constructor(components: any);
    /**
     * Creates a models dropdown element.
     *
     * @param config - Optional configuration.
     * @returns An HTMLElement containing the dropdown.
     */
    create(config?: ModelsDropdownConfig): HTMLElement;
}

/**
 * Built-in component that creates a dropdown listing all loaded BIM models.
 *
 * The dropdown auto-updates as models are loaded or unloaded via
 * {@link OBC.FragmentsManager}. Each option shows the model ID.
 *
 * @example
 * ```ts
 * const selector = components.get(ModelsDropdown);
 * const element = selector.create();
 * panel.appendChild(element);
 * ```
 */
export type ModelsDropdown = InstanceType<typeof _ModelsDropdown>;
/**
 * Built-in component that creates a dropdown listing all loaded BIM models.
 *
 * The dropdown auto-updates as models are loaded or unloaded via
 * {@link OBC.FragmentsManager}. Each option shows the model ID.
 *
 * @example
 * ```ts
 * const selector = components.get(ModelsDropdown);
 * const element = selector.create();
 * panel.appendChild(element);
 * ```
 */
export const ModelsDropdown = { uuid: '2496d0d7-ce8d-4683-92cb-615c524df0ca' } as typeof _ModelsDropdown & { uuid: '2496d0d7-ce8d-4683-92cb-615c524df0ca' };

/**
 * Configuration for creating a models panel.
 */
interface ModelsPanelConfig {
    /** Whether to show the load-model button. Defaults to `true`. */
    showLoadButton?: boolean;
    /** Custom element to use as load button instead of the default. */
    loadButton?: HTMLElement;
}
/**
 * Built-in component that creates a panel listing all loaded BIM models
 * with a search bar and optional load button.
 *
 * Uses `CUI.tables.modelsList()` from `@thatopen/ui-obc` to render
 * the model table with real-time updates as models are loaded/unloaded.
 *
 * @example
 * ```ts
 * const panel = components.get(ModelsPanel);
 * const element = panel.create(world);
 *
 * app.setup = {
 *   elements: { models: element, viewer: viewport },
 *   layouts: {
 *     Split: { template: `"models viewer" 1fr / 15rem 1fr` },
 *   },
 * };
 * ```
 */
declare class _ModelsPanel {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "28a40e22-d6c5-4103-b53e-37ddcc098435";
    enabled: boolean;
    readonly name = "ModelsPanel";
    constructor(components: any);
    /**
     * Creates a models panel element.
     *
     * @param world - The world whose models to display.
     * @param config - Optional configuration.
     * @returns An HTMLElement containing the models panel.
     */
    create(world: OBC.World, config?: ModelsPanelConfig): HTMLElement;
}

/**
 * Built-in component that creates a panel listing all loaded BIM models
 * with a search bar and optional load button.
 *
 * Uses `CUI.tables.modelsList()` from `@thatopen/ui-obc` to render
 * the model table with real-time updates as models are loaded/unloaded.
 *
 * @example
 * ```ts
 * const panel = components.get(ModelsPanel);
 * const element = panel.create(world);
 *
 * app.setup = {
 *   elements: { models: element, viewer: viewport },
 *   layouts: {
 *     Split: { template: `"models viewer" 1fr / 15rem 1fr` },
 *   },
 * };
 * ```
 */
export type ModelsPanel = InstanceType<typeof _ModelsPanel>;
/**
 * Built-in component that creates a panel listing all loaded BIM models
 * with a search bar and optional load button.
 *
 * Uses `CUI.tables.modelsList()` from `@thatopen/ui-obc` to render
 * the model table with real-time updates as models are loaded/unloaded.
 *
 * @example
 * ```ts
 * const panel = components.get(ModelsPanel);
 * const element = panel.create(world);
 *
 * app.setup = {
 *   elements: { models: element, viewer: viewport },
 *   layouts: {
 *     Split: { template: `"models viewer" 1fr / 15rem 1fr` },
 *   },
 * };
 * ```
 */
export const ModelsPanel = { uuid: '28a40e22-d6c5-4103-b53e-37ddcc098435' } as typeof _ModelsPanel & { uuid: '28a40e22-d6c5-4103-b53e-37ddcc098435' };

/**
 * Configuration for creating a QTO comparison list.
 */
interface QtoComparisonConfig {
    /** Whether to auto-update when the user selects elements. Defaults to `true`. */
    autoUpdate?: boolean;
    /** Message shown when fewer than 2 items are selected. */
    missingDataMessage?: string;
}
/**
 * Built-in component that creates a side-by-side property quantity
 * comparison table for two selected BIM elements.
 *
 * Auto-subscribes to the Highlighter's selection events so the table
 * updates whenever the user selects elements in the 3D view. Extracts
 * BaseQuantities from IFC `IsDefinedBy` relations and shows
 * Property / Item A / Item B / Difference columns.
 *
 * @example
 * ```ts
 * const qto = components.get(QtoComparisonList);
 * const element = qto.create(world);
 * panel.appendChild(element);
 * ```
 */
declare class _QtoComparisonList {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "48b2a34a-e52a-46d9-a195-4ea7c4cb272e";
    enabled: boolean;
    readonly name = "QtoComparisonList";
    constructor(components: any);
    /**
     * Creates a QTO comparison list element.
     *
     * @param world - The world with the loaded models.
     * @param config - Optional configuration.
     * @returns An HTMLElement containing the comparison table.
     */
    create(world: OBC.World, config?: QtoComparisonConfig): HTMLElement;
}

/**
 * Built-in component that creates a side-by-side property quantity
 * comparison table for two selected BIM elements.
 *
 * Auto-subscribes to the Highlighter's selection events so the table
 * updates whenever the user selects elements in the 3D view. Extracts
 * BaseQuantities from IFC `IsDefinedBy` relations and shows
 * Property / Item A / Item B / Difference columns.
 *
 * @example
 * ```ts
 * const qto = components.get(QtoComparisonList);
 * const element = qto.create(world);
 * panel.appendChild(element);
 * ```
 */
export type QtoComparisonList = InstanceType<typeof _QtoComparisonList>;
/**
 * Built-in component that creates a side-by-side property quantity
 * comparison table for two selected BIM elements.
 *
 * Auto-subscribes to the Highlighter's selection events so the table
 * updates whenever the user selects elements in the 3D view. Extracts
 * BaseQuantities from IFC `IsDefinedBy` relations and shows
 * Property / Item A / Item B / Difference columns.
 *
 * @example
 * ```ts
 * const qto = components.get(QtoComparisonList);
 * const element = qto.create(world);
 * panel.appendChild(element);
 * ```
 */
export const QtoComparisonList = { uuid: '48b2a34a-e52a-46d9-a195-4ea7c4cb272e' } as typeof _QtoComparisonList & { uuid: '48b2a34a-e52a-46d9-a195-4ea7c4cb272e' };

/**
 * Configuration for creating a queries hierarchy.
 */
interface QueriesHierarchyConfig {
    /**
     * Array of levels, each containing an array of query names.
     * The hierarchy is built recursively: level 0 items are parents,
     * level 1 items are children, etc.
     */
    queryHierarchy: string[][];
    /** Message shown when no hierarchy is defined. */
    missingDataMessage?: string;
}
/**
 * Built-in component that creates a recursive, multi-level query browser.
 *
 * Given a hierarchy of query names (e.g., zones → buildings → floors),
 * builds a nested table. Each row has an action button that runs the
 * accumulated path of queries via {@link OBC.ItemsFinder}, intersects
 * the results, and highlights matching elements.
 *
 * @example
 * ```ts
 * const tree = components.get(QueriesHierarchy);
 * const element = tree.create({
 *   queryHierarchy: [
 *     ['Zone A', 'Zone B'],
 *     ['Floor 1', 'Floor 2'],
 *   ],
 * });
 * panel.appendChild(element);
 * ```
 */
declare class _QueriesHierarchy {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "dcd02a90-4e8e-4699-9b76-b7d4d70e7231";
    enabled: boolean;
    readonly name = "QueriesHierarchy";
    constructor(components: any);
    /**
     * Creates a queries hierarchy table element.
     *
     * @param config - Configuration with the query hierarchy definition.
     * @returns An HTMLElement containing the hierarchy table.
     */
    create(config: QueriesHierarchyConfig): HTMLElement;
}

/**
 * Built-in component that creates a recursive, multi-level query browser.
 *
 * Given a hierarchy of query names (e.g., zones → buildings → floors),
 * builds a nested table. Each row has an action button that runs the
 * accumulated path of queries via {@link OBC.ItemsFinder}, intersects
 * the results, and highlights matching elements.
 *
 * @example
 * ```ts
 * const tree = components.get(QueriesHierarchy);
 * const element = tree.create({
 *   queryHierarchy: [
 *     ['Zone A', 'Zone B'],
 *     ['Floor 1', 'Floor 2'],
 *   ],
 * });
 * panel.appendChild(element);
 * ```
 */
export type QueriesHierarchy = InstanceType<typeof _QueriesHierarchy>;
/**
 * Built-in component that creates a recursive, multi-level query browser.
 *
 * Given a hierarchy of query names (e.g., zones → buildings → floors),
 * builds a nested table. Each row has an action button that runs the
 * accumulated path of queries via {@link OBC.ItemsFinder}, intersects
 * the results, and highlights matching elements.
 *
 * @example
 * ```ts
 * const tree = components.get(QueriesHierarchy);
 * const element = tree.create({
 *   queryHierarchy: [
 *     ['Zone A', 'Zone B'],
 *     ['Floor 1', 'Floor 2'],
 *   ],
 * });
 * panel.appendChild(element);
 * ```
 */
export const QueriesHierarchy = { uuid: 'dcd02a90-4e8e-4699-9b76-b7d4d70e7231' } as typeof _QueriesHierarchy & { uuid: 'dcd02a90-4e8e-4699-9b76-b7d4d70e7231' };

/**
 * Configuration for creating a screenshot annotator dialog.
 */
interface ScreenshotAnnotatorConfig {
    /** The screenshot image blob to annotate. */
    blob: Blob;
    /** Callback invoked when the user finishes annotating and clicks send. */
    onSend: (annotatedBlob: Blob) => Promise<void>;
    /** Callback invoked when the user cancels the annotation. */
    onCancel: () => Promise<void>;
    /** Label for the send button. Defaults to `"Send"`. */
    sendLabel?: string;
}
/**
 * Built-in component that creates a modal dialog for annotating
 * screenshots with arrows, text, and freehand drawings.
 *
 * Uses MarkerJS 3 (`@markerjs/markerjs3`) as an optional peer
 * dependency. The runtime must provide it as the `MARKERJS` global.
 *
 * Supports keyboard shortcuts: Delete to remove markers, Ctrl+Z to undo.
 * On send, the annotations are rasterized into a new image blob.
 *
 * @example
 * ```ts
 * const annotator = components.get(ScreenshotAnnotator);
 * const dialog = annotator.create({
 *   blob: screenshotBlob,
 *   onSend: async (blob) => { ... },
 *   onCancel: async () => { ... },
 * });
 * document.body.appendChild(dialog);
 * ```
 */
declare class _ScreenshotAnnotator {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "42a75a5a-2dac-49d7-9d1a-1e44f9d0dd56";
    enabled: boolean;
    readonly name = "ScreenshotAnnotator";
    constructor(components: any);
    /**
     * Creates a screenshot annotator dialog element.
     *
     * @param config - Configuration with the image blob and callbacks.
     * @returns An HTMLDialogElement containing the annotation UI.
     */
    create(config: ScreenshotAnnotatorConfig): HTMLDialogElement;
}

/**
 * Built-in component that creates a modal dialog for annotating
 * screenshots with arrows, text, and freehand drawings.
 *
 * Uses MarkerJS 3 (`@markerjs/markerjs3`) as an optional peer
 * dependency. The runtime must provide it as the `MARKERJS` global.
 *
 * Supports keyboard shortcuts: Delete to remove markers, Ctrl+Z to undo.
 * On send, the annotations are rasterized into a new image blob.
 *
 * @example
 * ```ts
 * const annotator = components.get(ScreenshotAnnotator);
 * const dialog = annotator.create({
 *   blob: screenshotBlob,
 *   onSend: async (blob) => { ... },
 *   onCancel: async () => { ... },
 * });
 * document.body.appendChild(dialog);
 * ```
 */
export type ScreenshotAnnotator = InstanceType<typeof _ScreenshotAnnotator>;
/**
 * Built-in component that creates a modal dialog for annotating
 * screenshots with arrows, text, and freehand drawings.
 *
 * Uses MarkerJS 3 (`@markerjs/markerjs3`) as an optional peer
 * dependency. The runtime must provide it as the `MARKERJS` global.
 *
 * Supports keyboard shortcuts: Delete to remove markers, Ctrl+Z to undo.
 * On send, the annotations are rasterized into a new image blob.
 *
 * @example
 * ```ts
 * const annotator = components.get(ScreenshotAnnotator);
 * const dialog = annotator.create({
 *   blob: screenshotBlob,
 *   onSend: async (blob) => { ... },
 *   onCancel: async () => { ... },
 * });
 * document.body.appendChild(dialog);
 * ```
 */
export const ScreenshotAnnotator = { uuid: '42a75a5a-2dac-49d7-9d1a-1e44f9d0dd56' } as typeof _ScreenshotAnnotator & { uuid: '42a75a5a-2dac-49d7-9d1a-1e44f9d0dd56' };

/**
 * Built-in component that creates a BIM viewer toolbar with common
 * 3D interaction controls.
 *
 * The toolbar includes visibility controls (Show All, Hide All),
 * selection-based actions (Focus, Hide, Isolate), and a color palette
 * for highlighting selected items.
 *
 * Uses {@link OBF.Highlighter} for selection state and color styles,
 * and {@link OBC.Hider} for visibility management.
 *
 * @example
 * ```ts
 * const toolbar = components.get(ViewerToolbar);
 * const element = toolbar.create(world);
 * document.body.appendChild(element);
 * ```
 */
declare class _ViewerToolbar {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "66f94e95-15c4-404b-bff9-c17ddedb6b3e";
    enabled: boolean;
    readonly name = "ViewerToolbar";
    constructor(components: any);
    /**
     * Creates a viewer toolbar element for the given world.
     *
     * @param world - The 3D world this toolbar controls.
     * @returns An HTMLElement containing the toolbar.
     */
    create(world: OBC.World): HTMLElement;
}

/**
 * Built-in component that creates a BIM viewer toolbar with common
 * 3D interaction controls.
 *
 * The toolbar includes visibility controls (Show All, Hide All),
 * selection-based actions (Focus, Hide, Isolate), and a color palette
 * for highlighting selected items.
 *
 * Uses {@link OBF.Highlighter} for selection state and color styles,
 * and {@link OBC.Hider} for visibility management.
 *
 * @example
 * ```ts
 * const toolbar = components.get(ViewerToolbar);
 * const element = toolbar.create(world);
 * document.body.appendChild(element);
 * ```
 */
export type ViewerToolbar = InstanceType<typeof _ViewerToolbar>;
/**
 * Built-in component that creates a BIM viewer toolbar with common
 * 3D interaction controls.
 *
 * The toolbar includes visibility controls (Show All, Hide All),
 * selection-based actions (Focus, Hide, Isolate), and a color palette
 * for highlighting selected items.
 *
 * Uses {@link OBF.Highlighter} for selection state and color styles,
 * and {@link OBC.Hider} for visibility management.
 *
 * @example
 * ```ts
 * const toolbar = components.get(ViewerToolbar);
 * const element = toolbar.create(world);
 * document.body.appendChild(element);
 * ```
 */
export const ViewerToolbar = { uuid: '66f94e95-15c4-404b-bff9-c17ddedb6b3e' } as typeof _ViewerToolbar & { uuid: '66f94e95-15c4-404b-bff9-c17ddedb6b3e' };

/**
 * The result of creating a viewport instance via {@link ViewportManager.create}.
 */
interface ViewportInstance {
    /** The `<bim-viewport>` HTML element to mount in a layout slot. */
    element: BUI.Viewport;
    /** The Three.js world bound to this viewport. */
    world: OBC.SimpleWorld<OBC.SimpleScene, OBC.OrthoPerspectiveCamera, OBC.SimpleRenderer>;
}
/**
 * Optional configuration when creating a viewport instance.
 */
interface ViewportConfig {
    /** Background color for the scene. Set to `null` for transparent. Defaults to `null`. */
    backgroundColor?: THREE.ColorRepresentation | null;
    /** Grid color. Defaults to `"lightgray"`. */
    gridColor?: THREE.ColorRepresentation;
}
/**
 * Built-in component that creates 3D viewports with a pre-configured
 * world (scene, camera, renderer) and fragments manager.
 *
 * ViewportManager is a factory: each call to {@link create} returns a
 * new independent viewport with its own world. The component tracks all
 * created instances and cleans them up on {@link dispose}.
 *
 * @example
 * ```ts
 * const viewports = components.get(ViewportManager);
 * const { element, world } = await viewports.create();
 *
 * // Use `element` as a slot in AppManager
 * app.setup = {
 *   elements: { viewer: element },
 *   layouts: { Main: { template: `"viewer" 1fr / 1fr` } },
 * };
 * ```
 */
declare class _ViewportManager {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "def81d43-6b44-4f4a-9c08-7649486112a4";
    enabled: boolean;
    readonly name = "ViewportManager";
    private _instances;
    private _fragmentsInitialized;
    constructor(components: any);
    /**
     * Creates a new viewport instance with its own world, scene, camera,
     * and renderer. Fragments manager is initialised automatically on
     * the first call.
     *
     * @param config - Optional visual configuration for the viewport.
     * @returns A {@link ViewportInstance} containing the DOM element and world.
     */
    create(config?: ViewportConfig): Promise<ViewportInstance>;
    /**
     * Disposes all created viewport instances and their worlds.
     */
    dispose(): void;
    /**
     * Initialises the fragments manager if not yet done, and wires up
     * model loading for the given world.
     */
    private _initFragments;
}

/**
 * Built-in component that creates 3D viewports with a pre-configured
 * world (scene, camera, renderer) and fragments manager.
 *
 * ViewportManager is a factory: each call to {@link create} returns a
 * new independent viewport with its own world. The component tracks all
 * created instances and cleans them up on {@link dispose}.
 *
 * @example
 * ```ts
 * const viewports = components.get(ViewportManager);
 * const { element, world } = await viewports.create();
 *
 * // Use `element` as a slot in AppManager
 * app.setup = {
 *   elements: { viewer: element },
 *   layouts: { Main: { template: `"viewer" 1fr / 1fr` } },
 * };
 * ```
 */
export type ViewportManager = InstanceType<typeof _ViewportManager>;
/**
 * Built-in component that creates 3D viewports with a pre-configured
 * world (scene, camera, renderer) and fragments manager.
 *
 * ViewportManager is a factory: each call to {@link create} returns a
 * new independent viewport with its own world. The component tracks all
 * created instances and cleans them up on {@link dispose}.
 *
 * @example
 * ```ts
 * const viewports = components.get(ViewportManager);
 * const { element, world } = await viewports.create();
 *
 * // Use `element` as a slot in AppManager
 * app.setup = {
 *   elements: { viewer: element },
 *   layouts: { Main: { template: `"viewer" 1fr / 1fr` } },
 * };
 * ```
 */
export const ViewportManager = { uuid: 'def81d43-6b44-4f4a-9c08-7649486112a4' } as typeof _ViewportManager & { uuid: 'def81d43-6b44-4f4a-9c08-7649486112a4' };
