/**
 * Built-in component types and runtime stubs.
 * Auto-generated by built-in-components/scripts/distribute.mjs
 */

declare class _HelloWorld {
    components: any;
    isDisposeable: () => this is any;
    isResizeable: () => this is any;
    isUpdateable: () => this is any;
    isHideable: () => this is any;
    isConfigurable: () => this is any;
    isSerializable: () => this is any;
    static readonly uuid: "2c4ae432-fc24-43e9-9783-0c960c674e96";
    enabled: boolean;
    readonly name = "HelloWorld";
    constructor(components: any);
    /**
     * Returns a greeting message and logs it to the console.
     * @param who - The name to greet. Defaults to `"World"`.
     */
    greet(who?: string): string;
}

/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export type HelloWorld = InstanceType<typeof _HelloWorld>;
/**
 * A simple test component to validate the built-in component pipeline.
 * Replace this with real components once the infrastructure is verified.
 */
export const HelloWorld = { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' } as typeof _HelloWorld & { uuid: '2c4ae432-fc24-43e9-9783-0c960c674e96' };
